FROM java:8
ARG PACKAGE_NAME
ARG PACKAGE_VERSION
ENV PACKAGE_NAME ${PACKAGE_NAME}
ENV PACKAGE_VERSION ${PACKAGE_VERSION}
RUN mkdir /app
COPY build/libs/${PACKAGE_NAME}-${PACKAGE_VERSION}.jar /app
EXPOSE 80
CMD ["java", "-jar", "/app/"${PACKAGE_NAME}"-"${PACKAGE_VERSION}".jar" ]
